#BEGIN_HEADER
#
# Copyright (C) 2020 Mahdi Safsafi.
#
# https://github.com/MahdiSafsafi/opcodesDB
#
# See licence file 'LICENCE' for use and distribution rights.
#
#END_HEADER

use strict;
use warnings;


STRINGIFY ENUM CTX_OP  => qw/NONE RCTX/;
STRINGIFY ENUM AT_OP   => qw/NONE S12E0R S12E0W S12E1R S12E1W S1E0R S1E0W S1E1R S1E1RP S1E1W S1E1WP S1E2R S1E2W S1E3R S1E3W/;
STRINGIFY ENUM IC_OP   => qw/NONE IALLU IALLUIS IVAU/;

STRINGIFY ENUM DC_OP   => qw/NONE CGDSW CGDVAC CGDVADP CGDVAP CGSW CGVAC CGVADP CGVAP CIGDSW CIGDVAC CIGSW 
                             CIGVAC CISW CIVAC CSW CVAC CVADP CVAP CVAU GVA GZVA IGDSW IGDVAC IGSW IGVAC ISW IVAC ZVA/;
						
STRINGIFY ENUM TLBI_OP => qw/NONE ALLE1 ALLE1IS ALLE1OS ALLE2 ALLE2IS ALLE2OS ALLE3 ALLE3IS ALLE3OS 
                        ASIDE1 ASIDE1IS ASIDE1OS IPAS2E1 IPAS2E1IS IPAS2E1OS IPAS2LE1 IPAS2LE1IS IPAS2LE1OS RIPAS2E1 
                        RIPAS2E1IS RIPAS2E1OS RIPAS2LE1 RIPAS2LE1IS RIPAS2LE1OS RVAAE1 RVAAE1IS RVAAE1OS RVAALE1 RVAALE1IS 
                        RVAALE1OS RVAE1 RVAE1IS RVAE1OS RVAE2 RVAE2IS RVAE2OS RVAE3 RVAE3IS RVAE3OS RVALE1 RVALE1IS RVALE1OS 
                        RVALE2 RVALE2IS RVALE2OS RVALE3 RVALE3IS RVALE3OS VAAE1 VAAE1IS VAAE1OS VAALE1 VAALE1IS VAALE1OS VAE1 
                        VAE1IS VAE1OS VAE2 VAE2IS VAE2OS VAE3 VAE3IS VAE3OS VALE1 VALE1IS VALE1OS VALE2 VALE2IS VALE2OS VALE3 
                        VALE3IS VALE3OS VMALLE1 VMALLE1IS VMALLE1OS VMALLS12E1 VMALLS12E1IS VMALLS12E1OS/;

STRINGIFY ENUM SYNC_OP => qw/NONE CSYNC/;

STRINGIFY ENUM PRF_OP   => qw/NONE PLDL1KEEP PLDL1STRM PLDL2KEEP PLDL2STRM PLDL3KEEP PLDL3STRM 
							 PSTL1KEEP PSTL1STRM PSTL2KEEP PSTL2STRM PSTL3KEEP PSTL3STRM PLIL1KEEP 
							 PLIL1STRM PLIL2KEEP PLIL2STRM PLIL3KEEP PLIL3STRM uimm4/;
				 
STRINGIFY ENUM PSTATEFIELD => qw/NONE DAIFClr DAIFSet DIT PAN SPSel SSBS TCO UAO/;



STRINGIFY ENUM PATTERN => qw/NONE ALL MUL3 MUL4 POW2 VL1 VL128 VL16 VL2 VL256 VL3 VL32 VL4 VL5 VL6 VL64 VL7 VL8 uimm5/;
STRINGIFY ENUM BTI_OP  => qw/NONE c j jc/;


OPTIONAL STRINGIFY ENUM NODE_TYPE => qw/NONE  
                AT_OP DC_OP IC_OP TLBI_OP SYNC_OP CTX_OP PRF_OP BTI_OP PSTATEFIELD BARRIER COND INVCOND
				BASE VBASE EBASE REG REGSH VREG EREG PREG REGOFF REGOFFSH VREGOFF VREGOFFSH VDS VDT      
				VLIST ELIST COUNT IDX
				SHIFTER SHIFT EXTEND AMOUNT PATTERN PATTERNSH 
                FPIMM IMM IMMSH IMMOFF IMMOFFSH LABEL ADDR
				MEM  SZ    
                CSPACE SYSREG    
                /;

OPTIONAL STRINGIFY ENUM SYMBOL => qw/NONE  amount at_op cond const 
                  dc_op extend fbits_right ic_op imm imm1 imm2 imm6 immr imms label 
				  aimm vfpimm advimm imm8 lsb mask mod nzcv op1 op2 
				  WideImmInverted WideImmAlias
                  option pattern pimm prfop pstatefield rotate shift shift_left shift_right shifter 
                  simm systemreg targets tlbi_op uimm4 uimm6 width
				  GPR32 GPR64 SIMD8 SIMD16 SIMD32 SIMD64 SIMD128 VECREG PRDREG SVEREG
				  Bd Bdn Bm Bn Bt Cm Cn Da Dd Ddn Dm Dn Dt Dt1 Dt2 Ha Hd Hdn Hm Hn Ht 
                  Pd Pdm Pdn Pg Pm Pn Pt Qd Qn Qt Qt1 Qt2 Sa Sd Sdn Sm Sn St St1 St2 Va Vd Vm Vn Vt 
                  Wa Wd Wdn Wm Wn Ws WsPair Wt Wt1 Wt2 WtPair Xa Xd Xdn Xm Xn Xs XsPair Xt Xt1 Xt2 XtPair 
                  ZM Za Zd Zda Zdn Zk Zm Zn Zn1 Zt Zt1
				  /;


#OPTIONAL ENUM EXCEPTION => qw/NONE AdvSIMDFPAccessTrap Alignment DataAbort ERetTrap FP 
#                     HypervisorCall MonitorCall PACFail PACTrap SPAlignment SVEAccessTrap
#                     SoftwareBreakpoint SupervisorCall TSTARTAccessTrap Uncategorized WFxTrap/;
 
# OPTIONAL ENUM EXTENSION => qw/NONE AES Atomic BF16 BTI Bit128PMULL CRC DGH DIT DOTP FCADD FJCVTZS 
#                     FP16 FP16MulNoRoundingToFP32 FlagFormat FlagManipulate Frint Int8MatMul MTE 
#                     PAC PAN QRDMLAH RAS SB SHA1 SHA256 SHA3 SHA512 SM3 SM4 SSBS 
#                     SVE SVE2 SVE2AES SVE2BitPerm SVE2PMULL128 SVE2SHA3 SVE2SM4 SVEFP32MatMul SVEFP64MatMul UAO/;

OPTIONAL STRINGIFY ENUM EXCEPTION => qw/NONE ADVSIMDFPACCESSTRAP ALIGNMENT DATAABORT ERETTRAP FP 
                     HYPERVISORCALL MONITORCALL PACFAIL PACTRAP SPALIGNMENT SVEACCESSTRAP
                     SOFTWAREBREAKPOINT SUPERVISORCALL TSTARTACCESSTRAP UNCATEGORIZED WFXTRAP/;

OPTIONAL STRINGIFY ENUM  EXTENSION => qw/NONE AES ATOMIC BF16 BTI BIT128PMULL CRC DGH DIT DOTP FCADD FJCVTZS 
                     FP16 FP16MULNOROUNDINGTOFP32 FLAGFORMAT FLAGMANIPULATE FRINT INT8MATMUL MTE 
                     PAC PAN QRDMLAH RAS SB SHA1 SHA256 SHA3 SHA512 SM3 SM4 SSBS 
                     SVE SVE2 SVE2AES SVE2BITPERM SVE2PMULL128 SVE2SHA3 SVE2SM4 SVEFP32MATMUL SVEFP64MATMUL UAO/;

OPTIONAL STRINGIFY ENUM VDT => qw/ NONE 16B 1D 1Q 2D 2H 2S 4B 4H 4S 8B 8H B D H Q S/;


1;